version: "3"
services:
  ts-node-docker-client:
    container_name: ts-node-docker-client
    user: "node"
    working_dir: /home/node/
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/home/node/src
      - ./public:/home/node/public:ro
      - ./package.json:/home/node/package.json
      - ./tsconfig.json:/home/node/tsconfig.json:ro
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres:5432/api-db
      NODE_ENV: development
    tty: true
    stdin_open: true
    ports:
      - '3001:3001'
    command: "npm start"